"""rev_23042022

Revision ID: 0313a6a1790c
Revises: e0fe49c5500e
Create Date: 2022-04-23 17:13:39.375077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0313a6a1790c'
down_revision = 'e0fe49c5500e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costo', sa.Column('costo', sa.Numeric(), nullable=True))
    op.drop_index('ix_costo_prezzo', table_name='costo')
    op.create_index(op.f('ix_costo_costo'), 'costo', ['costo'], unique=False)
    op.drop_column('costo', 'prezzo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costo', sa.Column('prezzo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_costo_costo'), table_name='costo')
    op.create_index('ix_costo_prezzo', 'costo', ['prezzo'], unique=False)
    op.drop_column('costo', 'costo')
    # ### end Alembic commands ###
