"""rev_30032022

Revision ID: 30d78e63ee1e
Revises: a3172b53ca18
Create Date: 2022-04-01 07:17:10.297890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d78e63ee1e'
down_revision = 'a3172b53ca18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('colore_preferito', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_cliente_colore_preferito'), 'cliente', ['colore_preferito'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cliente_colore_preferito'), table_name='cliente')
    op.drop_column('cliente', 'colore_preferito')
    # ### end Alembic commands ###
