"""rev_23042022

Revision ID: 5461b329c1b1
Revises: e9071c4b6a9f
Create Date: 2022-04-23 16:00:58.730102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5461b329c1b1'
down_revision = 'e9071c4b6a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.String(length=150), nullable=True),
    sa.Column('tipologia', sa.String(length=100), nullable=True),
    sa.Column('fatturazione', sa.String(length=100), nullable=True),
    sa.Column('costo', sa.String(length=100), nullable=True),
    sa.Column('data_inizio', sa.DateTime(), nullable=True),
    sa.Column('data_fine', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costo_costo'), 'costo', ['costo'], unique=False)
    op.create_index(op.f('ix_costo_data_creazione'), 'costo', ['data_creazione'], unique=False)
    op.create_index(op.f('ix_costo_data_fine'), 'costo', ['data_fine'], unique=False)
    op.create_index(op.f('ix_costo_data_inizio'), 'costo', ['data_inizio'], unique=False)
    op.create_index(op.f('ix_costo_descrizione'), 'costo', ['descrizione'], unique=False)
    op.create_index(op.f('ix_costo_fatturazione'), 'costo', ['fatturazione'], unique=False)
    op.create_index(op.f('ix_costo_note'), 'costo', ['note'], unique=False)
    op.create_index(op.f('ix_costo_tipologia'), 'costo', ['tipologia'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_costo_tipologia'), table_name='costo')
    op.drop_index(op.f('ix_costo_note'), table_name='costo')
    op.drop_index(op.f('ix_costo_fatturazione'), table_name='costo')
    op.drop_index(op.f('ix_costo_descrizione'), table_name='costo')
    op.drop_index(op.f('ix_costo_data_inizio'), table_name='costo')
    op.drop_index(op.f('ix_costo_data_fine'), table_name='costo')
    op.drop_index(op.f('ix_costo_data_creazione'), table_name='costo')
    op.drop_index(op.f('ix_costo_costo'), table_name='costo')
    op.drop_table('costo')
    # ### end Alembic commands ###
