"""inizialization

Revision ID: 728073645056
Revises: 
Create Date: 2022-03-04 09:20:50.938536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728073645056'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.String(length=50), nullable=True),
    sa.Column('descrizione', sa.String(length=100), nullable=True),
    sa.Column('costo', sa.Numeric(), nullable=True),
    sa.Column('data_attivazione', sa.DateTime(), nullable=True),
    sa.Column('scadenza_giorni', sa.Integer(), nullable=True),
    sa.Column('data_scadenza', sa.DateTime(), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_codice'), 'bot', ['codice'], unique=False)
    op.create_index(op.f('ix_bot_costo'), 'bot', ['costo'], unique=False)
    op.create_index(op.f('ix_bot_data_attivazione'), 'bot', ['data_attivazione'], unique=False)
    op.create_index(op.f('ix_bot_data_creazione'), 'bot', ['data_creazione'], unique=False)
    op.create_index(op.f('ix_bot_data_scadenza'), 'bot', ['data_scadenza'], unique=False)
    op.create_index(op.f('ix_bot_descrizione'), 'bot', ['descrizione'], unique=False)
    op.create_index(op.f('ix_bot_scadenza_giorni'), 'bot', ['scadenza_giorni'], unique=False)
    op.create_table('impostazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notifiche_mensili', sa.Boolean(), nullable=True),
    sa.Column('notifiche_scadenze_resi', sa.Boolean(), nullable=True),
    sa.Column('notifica_giorni_anticipo_resi', sa.Integer(), nullable=True),
    sa.Column('notifiche_scadenze_bot', sa.Boolean(), nullable=True),
    sa.Column('notifica_giorni_anticipo_bot', sa.Integer(), nullable=True),
    sa.Column('notifiche_scadenze_proxy', sa.Boolean(), nullable=True),
    sa.Column('notifica_giorni_anticipo_proxy', sa.Integer(), nullable=True),
    sa.Column('homepage_scadenze_resi', sa.Boolean(), nullable=True),
    sa.Column('homepage_giorni_anticipo_resi', sa.Integer(), nullable=True),
    sa.Column('homepage_scadenze_bot', sa.Boolean(), nullable=True),
    sa.Column('homepage_giorni_anticipo_bot', sa.Integer(), nullable=True),
    sa.Column('homepage_scadenze_proxy', sa.Boolean(), nullable=True),
    sa.Column('homepage_giorni_anticipo_proxy', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.String(length=50), nullable=True),
    sa.Column('descrizione', sa.String(length=100), nullable=True),
    sa.Column('stato', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('prezzo', sa.Numeric(), nullable=True),
    sa.Column('spedizione_acquisto', sa.Numeric(), nullable=True),
    sa.Column('reship', sa.Numeric(), nullable=True),
    sa.Column('slot', sa.Numeric(precision=100), nullable=True),
    sa.Column('data_ordine', sa.DateTime(), nullable=True),
    sa.Column('consegna_stesso_giorno', sa.Boolean(), nullable=True),
    sa.Column('data_consegna', sa.DateTime(), nullable=True),
    sa.Column('data_scadenza_reso', sa.DateTime(), nullable=True),
    sa.Column('proxy', sa.String(length=100), nullable=True),
    sa.Column('bot', sa.String(length=100), nullable=True),
    sa.Column('negozio', sa.String(length=100), nullable=True),
    sa.Column('taglia', sa.String(length=100), nullable=True),
    sa.Column('incasso', sa.Numeric(), nullable=True),
    sa.Column('spedizione_vendita', sa.Numeric(), nullable=True),
    sa.Column('fee_reship', sa.Numeric(), nullable=True),
    sa.Column('data_vendita', sa.DateTime(), nullable=True),
    sa.Column('incasso_stesso_giorno', sa.Boolean(), nullable=True),
    sa.Column('data_incasso', sa.DateTime(), nullable=True),
    sa.Column('canale', sa.String(length=100), nullable=True),
    sa.Column('contatto', sa.String(length=100), nullable=True),
    sa.Column('tipologia', sa.String(length=100), nullable=True),
    sa.Column('prezzo_totale', sa.Numeric(), nullable=True),
    sa.Column('ricavi_lordi', sa.Numeric(), nullable=True),
    sa.Column('ricavi_netti', sa.Numeric(), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_bot'), 'item', ['bot'], unique=False)
    op.create_index(op.f('ix_item_canale'), 'item', ['canale'], unique=False)
    op.create_index(op.f('ix_item_codice'), 'item', ['codice'], unique=False)
    op.create_index(op.f('ix_item_consegna_stesso_giorno'), 'item', ['consegna_stesso_giorno'], unique=False)
    op.create_index(op.f('ix_item_contatto'), 'item', ['contatto'], unique=False)
    op.create_index(op.f('ix_item_data_consegna'), 'item', ['data_consegna'], unique=False)
    op.create_index(op.f('ix_item_data_creazione'), 'item', ['data_creazione'], unique=False)
    op.create_index(op.f('ix_item_data_incasso'), 'item', ['data_incasso'], unique=False)
    op.create_index(op.f('ix_item_data_ordine'), 'item', ['data_ordine'], unique=False)
    op.create_index(op.f('ix_item_data_scadenza_reso'), 'item', ['data_scadenza_reso'], unique=False)
    op.create_index(op.f('ix_item_data_vendita'), 'item', ['data_vendita'], unique=False)
    op.create_index(op.f('ix_item_descrizione'), 'item', ['descrizione'], unique=False)
    op.create_index(op.f('ix_item_fee_reship'), 'item', ['fee_reship'], unique=False)
    op.create_index(op.f('ix_item_incasso'), 'item', ['incasso'], unique=False)
    op.create_index(op.f('ix_item_incasso_stesso_giorno'), 'item', ['incasso_stesso_giorno'], unique=False)
    op.create_index(op.f('ix_item_negozio'), 'item', ['negozio'], unique=False)
    op.create_index(op.f('ix_item_prezzo'), 'item', ['prezzo'], unique=False)
    op.create_index(op.f('ix_item_prezzo_totale'), 'item', ['prezzo_totale'], unique=False)
    op.create_index(op.f('ix_item_proxy'), 'item', ['proxy'], unique=False)
    op.create_index(op.f('ix_item_region'), 'item', ['region'], unique=False)
    op.create_index(op.f('ix_item_reship'), 'item', ['reship'], unique=False)
    op.create_index(op.f('ix_item_ricavi_lordi'), 'item', ['ricavi_lordi'], unique=False)
    op.create_index(op.f('ix_item_ricavi_netti'), 'item', ['ricavi_netti'], unique=False)
    op.create_index(op.f('ix_item_sku'), 'item', ['sku'], unique=False)
    op.create_index(op.f('ix_item_slot'), 'item', ['slot'], unique=False)
    op.create_index(op.f('ix_item_spedizione_acquisto'), 'item', ['spedizione_acquisto'], unique=False)
    op.create_index(op.f('ix_item_spedizione_vendita'), 'item', ['spedizione_vendita'], unique=False)
    op.create_index(op.f('ix_item_stato'), 'item', ['stato'], unique=False)
    op.create_index(op.f('ix_item_taglia'), 'item', ['taglia'], unique=False)
    op.create_index(op.f('ix_item_tipologia'), 'item', ['tipologia'], unique=False)
    op.create_table('negozio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.String(length=100), nullable=True),
    sa.Column('giorni_reso', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negozio_descrizione'), 'negozio', ['descrizione'], unique=False)
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.String(length=50), nullable=True),
    sa.Column('descrizione', sa.String(length=100), nullable=True),
    sa.Column('costo', sa.Numeric(), nullable=True),
    sa.Column('data_attivazione', sa.DateTime(), nullable=True),
    sa.Column('scadenza_giorni', sa.Integer(), nullable=True),
    sa.Column('data_scadenza', sa.DateTime(), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_codice'), 'proxy', ['codice'], unique=False)
    op.create_index(op.f('ix_proxy_costo'), 'proxy', ['costo'], unique=False)
    op.create_index(op.f('ix_proxy_data_attivazione'), 'proxy', ['data_attivazione'], unique=False)
    op.create_index(op.f('ix_proxy_data_creazione'), 'proxy', ['data_creazione'], unique=False)
    op.create_index(op.f('ix_proxy_data_scadenza'), 'proxy', ['data_scadenza'], unique=False)
    op.create_index(op.f('ix_proxy_descrizione'), 'proxy', ['descrizione'], unique=False)
    op.create_index(op.f('ix_proxy_scadenza_giorni'), 'proxy', ['scadenza_giorni'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxy_scadenza_giorni'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_descrizione'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_data_scadenza'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_data_creazione'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_data_attivazione'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_costo'), table_name='proxy')
    op.drop_index(op.f('ix_proxy_codice'), table_name='proxy')
    op.drop_table('proxy')
    op.drop_index(op.f('ix_negozio_descrizione'), table_name='negozio')
    op.drop_table('negozio')
    op.drop_index(op.f('ix_item_tipologia'), table_name='item')
    op.drop_index(op.f('ix_item_taglia'), table_name='item')
    op.drop_index(op.f('ix_item_stato'), table_name='item')
    op.drop_index(op.f('ix_item_spedizione_vendita'), table_name='item')
    op.drop_index(op.f('ix_item_spedizione_acquisto'), table_name='item')
    op.drop_index(op.f('ix_item_slot'), table_name='item')
    op.drop_index(op.f('ix_item_sku'), table_name='item')
    op.drop_index(op.f('ix_item_ricavi_netti'), table_name='item')
    op.drop_index(op.f('ix_item_ricavi_lordi'), table_name='item')
    op.drop_index(op.f('ix_item_reship'), table_name='item')
    op.drop_index(op.f('ix_item_region'), table_name='item')
    op.drop_index(op.f('ix_item_proxy'), table_name='item')
    op.drop_index(op.f('ix_item_prezzo_totale'), table_name='item')
    op.drop_index(op.f('ix_item_prezzo'), table_name='item')
    op.drop_index(op.f('ix_item_negozio'), table_name='item')
    op.drop_index(op.f('ix_item_incasso_stesso_giorno'), table_name='item')
    op.drop_index(op.f('ix_item_incasso'), table_name='item')
    op.drop_index(op.f('ix_item_fee_reship'), table_name='item')
    op.drop_index(op.f('ix_item_descrizione'), table_name='item')
    op.drop_index(op.f('ix_item_data_vendita'), table_name='item')
    op.drop_index(op.f('ix_item_data_scadenza_reso'), table_name='item')
    op.drop_index(op.f('ix_item_data_ordine'), table_name='item')
    op.drop_index(op.f('ix_item_data_incasso'), table_name='item')
    op.drop_index(op.f('ix_item_data_creazione'), table_name='item')
    op.drop_index(op.f('ix_item_data_consegna'), table_name='item')
    op.drop_index(op.f('ix_item_contatto'), table_name='item')
    op.drop_index(op.f('ix_item_consegna_stesso_giorno'), table_name='item')
    op.drop_index(op.f('ix_item_codice'), table_name='item')
    op.drop_index(op.f('ix_item_canale'), table_name='item')
    op.drop_index(op.f('ix_item_bot'), table_name='item')
    op.drop_table('item')
    op.drop_table('impostazioni')
    op.drop_index(op.f('ix_bot_scadenza_giorni'), table_name='bot')
    op.drop_index(op.f('ix_bot_descrizione'), table_name='bot')
    op.drop_index(op.f('ix_bot_data_scadenza'), table_name='bot')
    op.drop_index(op.f('ix_bot_data_creazione'), table_name='bot')
    op.drop_index(op.f('ix_bot_data_attivazione'), table_name='bot')
    op.drop_index(op.f('ix_bot_costo'), table_name='bot')
    op.drop_index(op.f('ix_bot_codice'), table_name='bot')
    op.drop_table('bot')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
