"""rev_21032022

Revision ID: 7afb1b06c717
Revises: cc1311a04bbb
Create Date: 2022-03-21 07:17:08.221636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afb1b06c717'
down_revision = 'cc1311a04bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('salva_rinnovo', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_bot_salva_rinnovo'), 'bot', ['salva_rinnovo'], unique=False)
    op.add_column('item', sa.Column('strategia', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_item_strategia'), 'item', ['strategia'], unique=False)
    op.add_column('proxy', sa.Column('salva_rinnovo', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_proxy_salva_rinnovo'), 'proxy', ['salva_rinnovo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxy_salva_rinnovo'), table_name='proxy')
    op.drop_column('proxy', 'salva_rinnovo')
    op.drop_index(op.f('ix_item_strategia'), table_name='item')
    op.drop_column('item', 'strategia')
    op.drop_index(op.f('ix_bot_salva_rinnovo'), table_name='bot')
    op.drop_column('bot', 'salva_rinnovo')
    # ### end Alembic commands ###
