"""rev_23042022

Revision ID: 8e4c2cb526b9
Revises: 0313a6a1790c
Create Date: 2022-04-23 18:17:59.103218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4c2cb526b9'
down_revision = '0313a6a1790c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costo_storico_pagamenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costo_id', sa.Integer(), nullable=True),
    sa.Column('descrizione', sa.String(length=100), nullable=True),
    sa.Column('costo', sa.Numeric(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['costo_id'], ['costo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costo_storico_pagamenti_costo'), 'costo_storico_pagamenti', ['costo'], unique=False)
    op.create_index(op.f('ix_costo_storico_pagamenti_data_creazione'), 'costo_storico_pagamenti', ['data_creazione'], unique=False)
    op.create_index(op.f('ix_costo_storico_pagamenti_data_pagamento'), 'costo_storico_pagamenti', ['data_pagamento'], unique=False)
    op.create_index(op.f('ix_costo_storico_pagamenti_descrizione'), 'costo_storico_pagamenti', ['descrizione'], unique=False)
    op.add_column('costo', sa.Column('data_prox_pagamento', sa.DateTime(), nullable=True))
    op.add_column('costo', sa.Column('data_ultimo_pagamento', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_costo_data_prox_pagamento'), 'costo', ['data_prox_pagamento'], unique=False)
    op.create_index(op.f('ix_costo_data_ultimo_pagamento'), 'costo', ['data_ultimo_pagamento'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_costo_data_ultimo_pagamento'), table_name='costo')
    op.drop_index(op.f('ix_costo_data_prox_pagamento'), table_name='costo')
    op.drop_column('costo', 'data_ultimo_pagamento')
    op.drop_column('costo', 'data_prox_pagamento')
    op.drop_index(op.f('ix_costo_storico_pagamenti_descrizione'), table_name='costo_storico_pagamenti')
    op.drop_index(op.f('ix_costo_storico_pagamenti_data_pagamento'), table_name='costo_storico_pagamenti')
    op.drop_index(op.f('ix_costo_storico_pagamenti_data_creazione'), table_name='costo_storico_pagamenti')
    op.drop_index(op.f('ix_costo_storico_pagamenti_costo'), table_name='costo_storico_pagamenti')
    op.drop_table('costo_storico_pagamenti')
    # ### end Alembic commands ###
