"""rev_23042022

Revision ID: d7465c4e188f
Revises: 063214640d24
Create Date: 2022-04-25 14:13:53.808068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7465c4e188f'
down_revision = '063214640d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costo_storico_pagamenti', sa.Column('note', sa.String(length=250), nullable=True))
    op.create_index(op.f('ix_costo_storico_pagamenti_note'), 'costo_storico_pagamenti', ['note'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_costo_storico_pagamenti_note'), table_name='costo_storico_pagamenti')
    op.drop_column('costo_storico_pagamenti', 'note')
    # ### end Alembic commands ###
