"""rev_23042022

Revision ID: e0fe49c5500e
Revises: 5461b329c1b1
Create Date: 2022-04-23 17:07:32.432049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fe49c5500e'
down_revision = '5461b329c1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costo', sa.Column('prezzo', sa.String(length=100), nullable=True))
    op.drop_index('ix_costo_costo', table_name='costo')
    op.create_index(op.f('ix_costo_prezzo'), 'costo', ['prezzo'], unique=False)
    op.drop_column('costo', 'costo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costo', sa.Column('costo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_costo_prezzo'), table_name='costo')
    op.create_index('ix_costo_costo', 'costo', ['costo'], unique=False)
    op.drop_column('costo', 'prezzo')
    # ### end Alembic commands ###
