"""rev_30032022

Revision ID: e9071c4b6a9f
Revises: 30d78e63ee1e
Create Date: 2022-04-01 07:37:01.612243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9071c4b6a9f'
down_revision = '30d78e63ee1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente_contatti', sa.Column('data_creazione', sa.DateTime(), nullable=True))
    op.add_column('cliente_contatti', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cliente_contatti_data_creazione'), 'cliente_contatti', ['data_creazione'], unique=False)
    op.create_foreign_key(None, 'cliente_contatti', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cliente_contatti', type_='foreignkey')
    op.drop_index(op.f('ix_cliente_contatti_data_creazione'), table_name='cliente_contatti')
    op.drop_column('cliente_contatti', 'user_id')
    op.drop_column('cliente_contatti', 'data_creazione')
    # ### end Alembic commands ###
